services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile.dev
    container_name: library-card-frontend
    volumes:
      - .:/var/www/html
      - node_modules:/var/www/html/node_modules
      - next_cache:/var/www/html/.next
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    stdin_open: true
    tty: true
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://127.0.0.1:3000",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  node_modules:
  next_cache:
